# yamllint disable-line rule:document-start
repos:
# yamllint disable-line rule:indentation
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks: [{id: black}]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks: [{id: ruff}, {id: ruff-format}]
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.9
  hooks:
  # yamllint disable-line rule:indentation
  - id: bandit
    args: ["-r", "backend", "-ll"]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  # yamllint disable-line rule:indentation
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-yaml
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks: [{id: detect-secrets}]
